### ISSUE TITLE
Bug: Highlighting is missed up when using Dollar $ sign

### ISSUE THREAD

**Issue by ditek** [jonschlinkert/sublime-markdown-extended#160]
Highlighting is missed up when using Dollar $ sign even if it is escaped (\$). This only affects highlighting. This file is still rendered correctly.
![image](https://cloud.githubusercontent.com/assets/10835824/23588852/e86db370-01c3-11e7-8626-740c1a39793c.png)

**Comment by sidwiesner** [comment]
I'm seeing the same problem. I keep all my notes in this file, and a normal $ appears around pricing and costs all over the place. I'm guessing this is related to the integration of LaTex changes, and that just impacted me starting this last week. I also am not able to escape the $, and only get back to normal highlighting in a file by putting in 4 of them in a row ($$$$).

**Comment by jonschlinkert** [comment]
Noted, I'll look into it. thanks for reporting.

**Comment by sidwiesner** [comment]
@jonschlinkert thanks. I added all my packages to ignored_packages except Package Control and Markdown Extended, then restarted Sublime Text (build 3126). I'm still seeing the same issue.

**Comment by sidwiesner** [comment]
It looks like it the latex-inline and latex-display matches are the issue. See https://github.com/jonschlinkert/sublime-markdown-extended/blob/master/Syntaxes/Markdown%20Extended.sublime-syntax#L1282

```
  latex-inline:
    - match: '(?=\$)'
      push:
        - meta_scope: text.tex.latex
        - match: '(?<=\$)'
          pop: true
        - include: scope:text.tex.latex

  latex-display:
    - match: '(?=\$\$)'
      push:
        - meta_scope: text.tex.latex
        - match: '(?<=\$\$)'
          pop: true
        - include: scope:text.tex.latex
```

If I use `$ $` or `$$ $$` separated by spaces, I can see the syntax highlighting terminate after those blocks.
